// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDriw1LxcT3UbhpfjTfq7vsSqgdsckrt4w',
    appId: '1:1029048019296:web:864f32ec1637b7bdc0d605',
    messagingSenderId: '1029048019296',
    projectId: 'driveguard-prototipo',
    authDomain: 'driveguard-prototipo.firebaseapp.com',
    storageBucket: 'driveguard-prototipo.firebasestorage.app',
    measurementId: 'G-PR2EQKZK1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc2V0mo4jOuFC7t11SMooYAQcjmvywUpQ',
    appId: '1:1029048019296:android:d9736696fe7886d7c0d605',
    messagingSenderId: '1029048019296',
    projectId: 'driveguard-prototipo',
    storageBucket: 'driveguard-prototipo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUOpzdS_1q0JkKaeWpbE7x6EBx2M_9vBc',
    appId: '1:1029048019296:ios:2e61bf91199930c8c0d605',
    messagingSenderId: '1029048019296',
    projectId: 'driveguard-prototipo',
    storageBucket: 'driveguard-prototipo.firebasestorage.app',
    iosBundleId: 'com.example.driveguardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUOpzdS_1q0JkKaeWpbE7x6EBx2M_9vBc',
    appId: '1:1029048019296:ios:2e61bf91199930c8c0d605',
    messagingSenderId: '1029048019296',
    projectId: 'driveguard-prototipo',
    storageBucket: 'driveguard-prototipo.firebasestorage.app',
    iosBundleId: 'com.example.driveguardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDriw1LxcT3UbhpfjTfq7vsSqgdsckrt4w',
    appId: '1:1029048019296:web:65ad2e444f7757cec0d605',
    messagingSenderId: '1029048019296',
    projectId: 'driveguard-prototipo',
    authDomain: 'driveguard-prototipo.firebaseapp.com',
    storageBucket: 'driveguard-prototipo.firebasestorage.app',
    measurementId: 'G-9RZ8ET3FRD',
  );
}
